<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="by Valentin Stefan - last update 08 November 2019" />


<title>bootstrapnet - Examples</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">bootstrapnet</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="examples.html">
    <span class="fa fa-gear"></span>
     
    Examples
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">bootstrapnet - Examples</h1>
<h4 class="author">by <a href="https://github.com/valentinitnelav">Valentin Stefan</a> - last update 08 November 2019</h4>

</div>


<div id="load-packages" class="section level1">
<h1>Load packages</h1>
<pre class="r"><code># Install bootstrapnet if not already done:
# install.packages(&quot;devtools&quot;)
# devtools::install_github(&quot;valentinitnelav/bootstrapnet&quot;)
library(bootstrapnet)
library(magrittr)
library(bipartite)</code></pre>
</div>
<div id="simulate-data" class="section level1">
<h1>Simulate data</h1>
<p>Generate two fictive networks from <code>bipartite::Safariland</code> to compare with <code>bootstrapnet</code> functionality:</p>
<pre class="r"><code>data(Safariland)

set.seed(321)
Safariland_1 &lt;- Safariland[, sort(sample.int(ncol(Safariland), 20))]
sum(Safariland_1) # number of interactions</code></pre>
<pre><code>## [1] 305</code></pre>
<pre class="r"><code>set.seed(123)
Safariland_2 &lt;- Safariland[, sort(sample.int(ncol(Safariland), 20))]
sum(Safariland_2)</code></pre>
<pre><code>## [1] 210</code></pre>
<p>Note that, <code>Safariland_1</code> has 305 interactions and <code>Safariland_2</code> has 210. This can give us an idea about the values we can use in the <code>start</code> and <code>step</code> arguments below. Presumably 10% of the interactions of the smallest network should suffice for <code>start.</code> And for <code>step</code> use 5% or 10%. Note that, very small <code>step</code> will require intensive CPU time and a very small <code>start</code> can result in many <code>NA</code> warnings because indices cannot be computed for the first small sampled networks.</p>
<pre class="r"><code>my_start &lt;- 50 # chosen higher than 20 to gain some CPU time
my_step &lt;- 20
my_n_boot &lt;- 50</code></pre>
</div>
<div id="network-level-indicesmetrics" class="section level1">
<h1>Network-level indices/metrics</h1>
<div id="nestedness" class="section level2">
<h2>nestedness</h2>
<p><strong>Resample two networks with computing “nestedness”.</strong></p>
<p>The two matrices (webs) are placed in a named list (<code>list(s1 = Safariland_1, s2 = Safariland_2)</code>), then the data is prepared with <code>web_matrix_to_df()</code>, which gives a suitable data format for the <code>boot_networklevel()</code> function, which further prepares the bootstrapped results for <code>ggplot</code>.</p>
<pre class="r"><code>lst_nest &lt;- list(s1 = Safariland_1, s2 = Safariland_2) %&gt;%
  lapply(web_matrix_to_df) %&gt;%
  boot_networklevel(col_lower = &quot;lower&quot;, # column name for plants
                    col_higher = &quot;higher&quot;, # column name for insects
                    index = &quot;nestedness&quot;,
                    level = &quot;both&quot;, # here, nestedness is not affected by level
                    start = my_start,
                    step = my_step,
                    n_boot = my_n_boot,
                    n_cpu = 3)</code></pre>
<!--
saveRDS(lst_nest, file = "./man/cache/README-example-nestedness-1-lst.rds")
-->
<p>Plot the bootstrap results for the two webs.</p>
<pre class="r"><code>gg_networklevel(lst_nest)</code></pre>
<pre><code>## $nestedness</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The dashed lines represent the quantile based 95% confidence intervals. The continuous thicker lines represent the mean values at different sample sizes. The final sample sizes are actually the entire webs (total number of interactions). Each bootstrap/iteration is represented by a thinner transparent line.</p>
</div>
<div id="niche-overlap" class="section level2">
<h2>niche overlap</h2>
<p><strong>Resample two networks with computing “niche overlap”.</strong></p>
<p>The computation here is carried for both species levels (lower and higher, so plants and insects). If you are interested only in one level, then specify that with the parameter <code>level</code> (<code>level = 'lower'</code> or <code>level = 'higher'</code>).</p>
<pre class="r"><code>lst_niov &lt;- list(s1 = Safariland_1, s2 = Safariland_2) %&gt;%
  lapply(web_matrix_to_df) %&gt;%
  boot_networklevel(col_lower = &quot;lower&quot;, # column name for plants
                    col_higher = &quot;higher&quot;, # column name for insects
                    index = &quot;niche overlap&quot;,
                    level = &quot;both&quot;, # for both levels (lower &amp; higher)
                    start = my_start,
                    step = my_step,
                    n_boot = my_n_boot,
                    n_cpu = 3)</code></pre>
<!--
saveRDS(lst_niov, file = "man/cache/README-example-niche-overlap-1-lst.rds")
-->
<p>Plot the bootstrap results.</p>
<pre class="r"><code>niov_gg &lt;- gg_networklevel(lst_niov)
niov_gg$niche.overlap.HL # for higher level species</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>niov_gg$niche.overlap.LL # for lower level species</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
</div>
</div>
<div id="species-level-indicesmetrics" class="section level1">
<h1>Species-level indices/metrics</h1>
<div id="betweenness" class="section level2">
<h2>betweenness</h2>
<p><strong>Resample two networks with computing “betweenness”.</strong></p>
<p>Compare “betweenness” of ‘Alstroemeria aurea’ (lower level species) between the two networks. Also compare the betweenes of ‘Allograpta.Toxomerus’ (higher level species).</p>
<p>If you are interested only in the lower or higher level species computations, then set the parameter <code>level</code> accordingly (<code>level = 'lower'</code> or <code>level = 'higher'</code>). In such cases, then specify only one of the <code>sp_lower</code> and <code>sp_higher</code> in the plotting functions <code>gg_specieslevel_compare_webs</code> or <code>gg_specieslevel_web_by_web</code>.</p>
<pre class="r"><code>lst_btw &lt;- list(s1 = Safariland_1, s2 = Safariland_2) %&gt;%
  lapply(web_matrix_to_df) %&gt;%
  boot_specieslevel(col_lower = &quot;lower&quot;, # column name for plants
                    col_higher = &quot;higher&quot;, # column name for insects
                    index = &quot;betweenness&quot;,
                    level = &quot;both&quot;, # for both levels (lower &amp; higher)
                    start = my_start,
                    step = my_step,
                    n_boot = my_n_boot,
                    n_cpu = 3)</code></pre>
<!--
saveRDS(lst_btw, file = "man/cache/README-example-betweenness-1-lst.rds")
-->
<p>Plot the bootstrap results.</p>
<pre class="r"><code>btw_comp_Aa_At_gg &lt;- lst_btw %&gt;%
  get_stats_multi() %&gt;%
  gg_specieslevel_compare_webs(sp_lower = &quot;Alstroemeria aurea&quot;,
                               sp_higher = &quot;Allograpta.Toxomerus&quot;)
btw_comp_Aa_At_gg # plot all</code></pre>
<pre><code>## $higher_level</code></pre>
<pre><code>## Warning: Removed 32 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre><code>## 
## $higher_level_weighted</code></pre>
<pre><code>## Warning: Removed 32 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<pre><code>## 
## $lower_level</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-10-3.png" width="672" /></p>
<pre><code>## 
## $lower_level_weighted</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-10-4.png" width="672" /></p>
<p>Plot resampled betweenness of all species at both levels of selected common species.</p>
<p>Selected common species:</p>
<pre class="r"><code>common_lower_sp &lt;- intersect(rownames(Safariland_1), rownames(Safariland_2))
common_higher_sp &lt;- intersect(colnames(Safariland_1), colnames(Safariland_2))

btw_sp_webs_gg &lt;- lst_btw %&gt;%
  gg_specieslevel_web_by_web(sp_lower = common_lower_sp[1:5],
                             sp_higher = common_higher_sp[1:5])

btw_sp_webs_gg</code></pre>
<pre><code>## $s1.higher_level</code></pre>
<pre><code>## Warning: Removed 775 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre><code>## 
## $s1.higher_level_weighted</code></pre>
<pre><code>## Warning: Removed 780 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<pre><code>## 
## $s1.lower_level</code></pre>
<pre><code>## Warning: Removed 266 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-3.png" width="672" /></p>
<pre><code>## 
## $s1.lower_level_weighted</code></pre>
<pre><code>## Warning: Removed 540 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-4.png" width="672" /></p>
<pre><code>## 
## $s2.higher_level</code></pre>
<pre><code>## Warning: Removed 482 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-5.png" width="672" /></p>
<pre><code>## 
## $s2.higher_level_weighted</code></pre>
<pre><code>## Warning: Removed 482 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-6.png" width="672" /></p>
<pre><code>## 
## $s2.lower_level</code></pre>
<pre><code>## Warning: Removed 24 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-7.png" width="672" /></p>
<pre><code>## 
## $s2.lower_level_weighted</code></pre>
<pre><code>## Warning: Removed 198 rows containing missing values (geom_path).</code></pre>
<p><img src="examples_files/figure-html/unnamed-chunk-11-8.png" width="672" /></p>
<p>To plot betweenness of all species at all levels for each web/network, just leave the parameters <code>sp_lower</code> and <code>sp_higher</code> to default to <code>NULL</code>.</p>
<pre class="r"><code>btw_sp_webs_gg_all &lt;- lst_btw %&gt;%
  gg_specieslevel_web_by_web()</code></pre>
<pre><code>## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_higher` not provided, all higher level species will be used!

## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_higher` not provided, all higher level species will be used!</code></pre>
<pre><code>## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_lower` not provided, all lower level species will be used!

## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_lower` not provided, all lower level species will be used!</code></pre>
<pre><code>## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_higher` not provided, all higher level species will be used!

## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_higher` not provided, all higher level species will be used!</code></pre>
<pre><code>## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_lower` not provided, all lower level species will be used!

## Warning in filter_species(lst = metrics_stats[[i]], sp_lower = sp_lower, :
## `sp_lower` not provided, all lower level species will be used!</code></pre>
</div>
</div>
<div id="r-session-info" class="section level1">
<h1>R Session info</h1>
<pre class="r"><code>sessionInfo()</code></pre>
<pre><code>## R version 3.6.1 (2019-07-05)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 7 x64 (build 7601) Service Pack 1
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] bipartite_2.13          sna_2.4                 network_1.15           
## [4] statnet.common_4.3.0    vegan_2.5-6             lattice_0.20-38        
## [7] permute_0.9-5           magrittr_1.5            bootstrapnet_0.0.0.9000
## 
## loaded via a namespace (and not attached):
##  [1] spam_2.4-0         tidyselect_0.2.5   xfun_0.10         
##  [4] purrr_0.3.3        splines_3.6.1      colorspace_1.4-1  
##  [7] vctrs_0.2.0        htmltools_0.4.0    yaml_2.2.0        
## [10] mgcv_1.8-28        rlang_0.4.1        pillar_1.4.2      
## [13] glue_1.3.1         matrixStats_0.54.0 foreach_1.4.7     
## [16] lifecycle_0.1.0    stringr_1.4.0      fields_9.9        
## [19] dotCall64_1.0-0    munsell_0.5.0      gtable_0.3.0      
## [22] evaluate_0.14      codetools_0.2-16   coda_0.19-3       
## [25] labeling_0.3       knitr_1.25         doParallel_1.0.15 
## [28] parallel_3.6.1     Rcpp_1.0.2         scales_1.0.0      
## [31] backports_1.1.5    ggplot2_3.2.1      digest_0.6.22     
## [34] stringi_1.4.3      dplyr_0.8.3        grid_3.6.1        
## [37] tools_3.6.1        maps_3.3.0         lazyeval_0.2.2    
## [40] tibble_2.1.3       cluster_2.1.0      crayon_1.3.4      
## [43] tidyr_1.0.0        pkgconfig_2.0.3    zeallot_0.1.0     
## [46] MASS_7.3-51.4      ellipsis_0.3.0     Matrix_1.2-17     
## [49] data.table_1.12.6  rmarkdown_1.16     assertthat_0.2.1  
## [52] rstudioapi_0.10    iterators_1.0.12   R6_2.4.0          
## [55] igraph_1.2.4.1     nlme_3.1-141       compiler_3.6.1</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
